subscription/urls.py
# urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .views import subscribe_to_plan, subscribe_success

app_name = 'subscription'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('plans/', views.plans, name='plans'),
    path('register/', views.register, name='register'),
    path('view_profile/', views.profile_view, name='view-profile'),
    path('profile/', views.manage_profile, name='manage_profile'),
    path('login/', auth_views.LoginView.as_view(template_name='subscription/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('subscribe/<int:plan_id>/', subscribe_success, name='subscribe_to_plan'),
    path('networks/', views.available_networks, name='available_networks'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from mpesa.urls import mpesa_urls
from mpesa import views as mpesa_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subscription.urls', namespace='subscription')),
    path('mpesa/', include(mpesa_urls)),
    
]

subscription/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

class ServicePlan(models.Model):
    name = models.CharField(max_length=50)
    duration_hours = models.IntegerField()
    bandwidth_limit_mb = models.IntegerField()
    device_limit = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    phone_number = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.name

class SubscriberProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, blank=True)
    plan = models.ForeignKey(ServicePlan, on_delete=models.SET_NULL, null=True)
    plan_activated = models.DateTimeField(null=True, blank=True)
    plan_expires = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    mac_address = models.CharField(max_length=17, blank=True, null=True)
    ip_address = models.GenericIPAddressField(blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile_pics/', default='profile_pics/default.jpg')

    def __str__(self):
        return self.user.username
    
    def activate_plan(self, plan):
        self.plan = plan
        self.plan_activated = timezone.now()
        self.plan_expires = timezone.now() + timedelta(hours=plan.duration_hours)
        self.save()

class Device(models.Model):
    subscriber = models.ForeignKey(SubscriberProfile, on_delete=models.CASCADE)
    mac_address = models.CharField(max_length=17)
    device_name = models.CharField(max_length=50, blank=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.device_name or self.mac_address}"

class UsageRecord(models.Model):
    subscriber = models.ForeignKey(SubscriberProfile, on_delete=models.CASCADE)
    session_start = models.DateTimeField()
    session_end = models.DateTimeField(null=True, blank=True)
    data_used_mb = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"Usage for {self.subscriber.user.username} on {self.session_start}"
    
# model for mpesa payment for the subscription plan chosen
class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(ServicePlan, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    paid = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

subscription/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from .models import SubscriberProfile

class UserRegistrationForm(forms.ModelForm):
    model= SubscriberProfile
    password = forms.CharField(widget=forms.PasswordInput)
    mac_address = forms.CharField(max_length=17)
    ip_address = forms.GenericIPAddressField()
    profile_pic = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=15)
    

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'mac_address', 'ip_address']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            profile = user.subscriberprofile  # assuming a post_save signal creates it
            profile.profile_pic = self.cleaned_data.get('profile_pic')
            profile.mac_address = self.cleaned_data.get('mac_address')
            profile.ip_address = self.cleaned_data.get('ip_address')
            profile.phone_number = self.cleaned_data.get('phone_number')
            profile.save()
        return user

class ProfileUpdateForm(forms.ModelForm):
    model = SubscriberProfile
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(max_length=15)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    profile_pic = forms.ImageField(required=False)
    

    class Meta:
        model = SubscriberProfile
        fields = ['mac_address', 'ip_address']

    def __init__(self, *args, user=None, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            profile = user.subscriberprofile  # assuming a post_save signal creates it
            profile.profile_pic = self.cleaned_data.get('profile_pic')
            profile.save()
        return user

    

subscription/views.py
# views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, ProfileUpdateForm
from django.contrib.auth.models import User
from .models import SubscriberProfile, Payment
from django.contrib.auth import login
from .models import*
from django.shortcuts import get_object_or_404, redirect
from .models import Payment
from django.http import JsonResponse
from mpesa import Auth, STKPush
from django.views.decorators.http import require_POST
from decouple import config
from django.http import JsonResponse
from .utils import scan_networks, connect_to_network
from mpesa.urls import mpesa_urls
from mpesa import*
from django.urls import reverse
import requests


def welcome(request):
    return render(request, 'subscription/welcome.html')

@require_POST
def initiate_stk(request):
    phone = request.POST['phone']
    amount = request.POST['amount']

    # Authenticate using values populated via .env
    auth = Auth(
        consumer_key=None,  # passes through Config
        consumer_secret=None,
        base_url=None
    )
    auth_data = auth.get_access_token()
    token = auth_data.get('access_token')

    stk = STKPush(base_url=None, access_token=token)

    timestamp = stk.generate_timestamp()
    payload = stk.create_payload(
        BusinessShortCode=request.POST.get('short_code', '174379'),
        pass_key=request.POST.get('pass_key'),
        Timestamp=timestamp,
        TransactionType='CustomerPayBillOnline',
        Amount=amount,
        PartyA=phone,
        PartyB=request.POST.get('short_code', '174379'),
        PhoneNumber=phone,
        CallBackURL=request.build_absolute_uri('/mpesa/callback/'),
        AccountReference='REF123',
        TransactionDesc='ISP Subscription'
    )

    response = stk.send_stk_push(payload)
    return JsonResponse(response)
@login_required
def dashboard(request):
    profile, _ = SubscriberProfile.objects.get_or_create(user=request.user)
    return render(request, 'subscription/dashboard.html', {
        'user': request.user,
        'profile':profile,
    })
def plans(request):
    plans = ServicePlan.objects.all()
    return render(request, 'subscription/plans.html', {'plans':plans})


@login_required
def subscribe_to_plan(request, plan_id):
    plan = ServicePlan.objects.get(pk=plan_id)
    profile = request.user.subscriberprofile
    phone = request.user.subscriberprofile.phone_number
    
    stk_endpoint = request.build_absolute_uri(reverse('submit'))
    resp = requests.post(stk_endpoint, data={
        'amount': plan.price,
        'phone_number': request.user.subscriberprofile.phone_number,
        'account_number': f"Plan-{plan.id}",
    })
    return redirect('subscribe_success', plan_id=plan.id)
@login_required
def subscribe_success(request, plan_id):
    plan = ServicePlan.objects.get(pk=plan_id)
    return render(request, 'subscription/subscribe_success.html', {
        'plan': plan,
        'message': "STK Push sent! Check your phone to complete payment."
    })
# views.py
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
    else:
        form = UserRegistrationForm()
    return render(request, 'subscription/register.html', {'form': form})



@login_required
def manage_profile(request):
    profile = request.user.subscriberprofile
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.subscriberprofile)
        if form.is_valid():
            form.save()
            return redirect('manage_profile')
    else:
        form = ProfileUpdateForm(instance=profile, initial={
            'email': request.user.email,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            
        }, user=request.user)
    return render(request, 'subscription/manage-profile.html', {'form': form})
@login_required
def profile_view(request):
    profile = request.user.subscriberprofile
    return render(request, "subscription/profile.html", {"profile": profile})


def available_networks(request):
    if request.method == 'POST':
        ssid = request.POST['ssid']
        password = request.POST.get('password','')
        success = connect_to_network(ssid, password)
        return render(request, 'subscription/networks_list.html', {
            'networks': scan_networks(),
            'message': f"Connected to {ssid}" if success else f"Failed to connect to {ssid}"
        })
    return render(request, 'subscription/networks_list.html', {
        'networks': scan_networks()
    
    })

subscription/templates/subscription/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>wifi management</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 550px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #a9dbcb;
      height: 100%;
    }
        
    /* On small screens, set height to 'auto' for the grid */
    @media screen and (max-width: 767px) {
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Empire network</a></li>
        <li><a href="{% url 'subscription:view_profile %'}">profile</a></li>
        <li><a href="{% url 'subscription:plans' %}">plans</a></li>
        <li><a href="{% url 'subscription:logout' %}">Logout</a></li>
        <li><a href="#">connect</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h2>Logo</h2>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="{% url 'subscription:plans' %}">Empire</a></li>
        <li class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">Profile
          <ul>          
            <li><a class="dropdown-item" href="{% url 'subscription:manage_profile' %}">my profile</a></li>
            <li><a class="dropdown-item" href="{% url 'subscription:view-profile' %}">manage profile</a></li>
            <li><a class="dropdown-item" href="{% url 'subscription:logout' %}">Log out</a></li>
          </ul>
        </li>
        <li><a href="{% url 'subscription:plans' %}">plans</a></li>
        <li><a href="{% url 'subscription:available_networks' %}">speed</a></li>
        
      </ul><br>
    </div>
    <br>
    
    <div class="col-sm-9">
      <div class="well"  style="background-color: aqua;">
        <h4>Empire connections</h4>
        <p>Some text..</p>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well" style="background-color: #a8f75e;">
            <h4>plans</h4>
            <p>1 Million</p> 
          </div>
        </div>
        <div class="col-sm-3">
          <div class="well" style="background-color: #251f75;">
            <h4>status</h4>
            <p>100 Million</p> 
          </div>
        </div>
        <div class="col-sm-3">
          <div class="well" style="background-color: #db62c1;">
            <h4>history</h4>
            <p>10 Million</p> 
          </div>
        </div>
        <div class="col-sm-3">
          <div class="well">
            <h4>Bounce</h4>
            <p>30%</p> 
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
            <p>Text</p> 
            <p>Text</p> 
          </div>
        </div>
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
            <p>Text</p> 
            <p>Text</p> 
          </div>
        </div>
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
            <p>Text</p> 
            <p>Text</p> 
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8">
          <div class="well">
            <p>Text</p> 
          </div>
        </div>
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

subscription/templates/subscription/login.html
<!-- templates/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login</title>
</head>
<body>
  <div class="container-fluid">
    <div class="col-sm-3">
      <div class="well">
        <h2>Login to Your Account</h2>
      </div>
    </div>
    
    {% if form.errors %}
      <p style="color: red;">Invalid username or password.</p>
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <label>Username:</label>
      {{ form.username }}<br><br>

      <label>Password:</label>
      {{ form.password }}<br><br>

      <a href="{% url 'subscription:login' %}"><button type="submit">Login</button></a>
    </form>
  </div>
</body>
</html>

subscription/templates/subscription/manage-profile.html
<!-- templates/manage_profile.html -->
<!DOCTYPE html>
<html>
<head>
  <title>Manage Profile</title>
</head>
<body>
  <h2>Update Profile</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
   <a href="{% url 'subscription:manage_profile' %}"> <button type="submit">Save Changes</button></a>
  </form>
</body>
</html>

subscription/templates/subscription/networks_list.html
{% block content %}
  <h2>Available Wi‑Fi Networks</h2>
  {% if message %}
    <div class="alert alert-info">{{ message }}</div>
  {% endif %}
  <table class="table">
    <thead><tr><th>#</th><th>SSID</th><th>Signal</th><th>Action</th></tr></thead>
    <tbody>
      {% for net in networks %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ net.ssid }}</td>
        <td>{{ net.signal }} dBm</td>
        <td>
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="ssid" value="{{ net.ssid }}">
            <input name="password" placeholder="Password">
            <button class="btn btn-sm" href="{% url 'subscription:available_networks' %}">Connect</button>
          </form>
        </td>
      </tr>
      {% empty %}
        <tr><td colspan="4">No networks found</td></tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

subscription/templates/subscription/plans.html
<!-- templates/dashboard.html -->
<!DOCTYPE html>
<html>
<head>
  <title>Amazing Plans!!!</title>
</head>
<body>
  <h2>Welcome {{ request.user.username }}</h2> <!--displaying username logged in-->

  <h3>Available Service Plans</h3>
  <ul>
    {% for plan in plans %} <!--listing all the plans added from the backend-->
      <li>
        <strong>{{ plan.name }}</strong><br>
        Duration: {{ plan.duration_hours }} hours<br>
        Bandwidth: {{ plan.bandwidth_limit_mb }} MB<br>
        Price: KES {{ plan.price }}<br>
        <p>{{ plan.description }}</p>
      </li>
      <!--adding subscribe button to the plans-->
    {% if request.user.subscriberprofile.plan == plan %}
        <em>You are currently subscribed to this plan.</em>
      {% else %}
        <form method="post" action="{% url 'subscription:subscribe_to_plan' plan.id  %}">
          {% csrf_token %}
          <button type="submit", style="background-color: rgb(115, 130, 196);">Subscribe</button>
        </form>
      {% endif %}
    


    {% empty %}
      <p>No plans available at the moment.</p>
    {% endfor %}

  </ul>
</body>
</html>

subscription/templates/subscription/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Bootstrap CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'subscription:view-profile' %}">My profile</a>
    <div class="collapse navbar-collapse">
      <!-- Left nav omitted for brevity -->
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle d-flex align-items-center" href="{% url 'subscription:dashboard' %}" id="profileDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.subscriberprofile.profile_pic %}
                <img src="{{ user.subscriberprofile.profile_pic.url }}" alt="Profile" class="rounded-circle" width="70" height="100">
              {% else %}
                <img src="{% static 'images/default-avatar.jpg' %}" alt="Default Avatar" class="rounded-circle" width="32" height="32">
              {% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
            <li><a class="dropdown-item" href="{% url 'subscription:manage_profile' %}">Profile</a></li>
            <li>
              <form method="post" action="{% url 'subscription:logout' %}" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">Logout</button>
              </form>
            </li>
          </ul>
        </li>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'subscription:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">{% block content %}{% endblock %}</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

subscription/templates/subscription/register.html
<!-- templates/register.html -->
<!DOCTYPE html>
<html>
<head>
  <title>Register</title>
</head>
<body>
  <h2>Register</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
</body>
</html>

subscription/templates/subscription/subscribe_success.html
{% load static %}
{% load i18n %}

{% block title %}Subscription Initiated{% endblock %}

{% block content %}
<section class="subscription-success">
  <div class="container">
    <h1>{% trans "Subscription Initiated" %}</h1>
    <p>{% trans "We have sent an M‑Pesa STK prompt to your phone." %}</p>
    <p>{% trans "Please enter your PIN on your device to complete the payment." %}</p>
    
    {% if plan %}
      <div class="plan-summary">
        <strong>{% trans "Plan:" %}</strong> {{ plan.name }} <br>
        <strong>{% trans "Amount:" %}</strong> KES {{ plan.price }} <br>
        <strong>{% trans "Phone Number:" %}</strong> {{ request.user.subscriberprofile.phone_number }}
      </div>
    {% endif %}

    <a href="{% url 'subscription:dashboard' %}" class="btn btn-primary">
      {% trans "Go to Dashboard" %}
    </a>
  </div>
</section>
{% endblock %}

subscription/templates/subscription/welcome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Landing page</title>
  <style>
    .root{
        background-color: rgb(163, 55, 55);
    }
    .h2{
        text-align: center;
    }
  </style>

</head>
<body style="background-color: plum;">
  <div class="container-fluid">
    <div class="col-sm-3">
      <div class="well" style="text-align: center;">
        <h2>WELCOME TO EMPIRE CONNECTIONS</h2>
      </div>
    </div>
  <div class="container-fluid">
    <div class="col-sm-3">
      <div class="well" style="text-align: center;">
      <a href="{% url 'subscription:login' %}"><button type="submit" style="text-align: center; background-color: greenyellow;">WELCOME</button></a>
      </div>
    </div>
  </div>
  </div>
  <div class="col-sm-3">
          <div class="well" style="text-align: center;">
            <h4 style="text-emphasis-color: yellow;">are you new?</h4>
            <a href="{% url 'subscription:register' %}"<button type="submit">sign-up-to-connect</button> </a>
          </div>
  </div>
</body>
</html>